version: '3.8'

services:
  product_db:
    image: postgres:16-alpine
    container_name: product_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwer
      POSTGRES_DB: products_db
    ports:
      - "5111:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: