version: '3.8'

services:
  category-db:
    image: postgres:16-alpine
    container_name: category-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwer
      POSTGRES_DB: category_db
    ports:
      - "5112:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: